# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98fa9329cc67e924bb9eb8702026fd450f30cf3bc1d69a24ed497f6c7001e1a9e11a58db441ab0682d526c2aa4a214c91284e867cb4b8dafcad27f33c4a143aa

test:
  secret_key_base: 97f18f822ed5c8157a5070bcbd04b5b019d5eae0e79d339a9a04cf86762d6aba03141643f5b831684ec7d6e878c3e370e8da1e5e98296b05830ca7680c03f5e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
